[project]
name = "base"
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[dependencies]
python = "3.11.*"
numpy = "*"
pandas = "*"
matplotlib = "*"
jupyter = "*"
ipython = "*"
scikit-learn = "*"
